# Generated by Django for portfolio models.

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name="ContactFormEntry",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("name", models.CharField(max_length=120)),
        ("email", models.EmailField(max_length=254)),
        ("subject", models.CharField(max_length=180)),
        ("message", models.TextField()),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("is_responded", models.BooleanField(default=False)),
      ],
      options={
        "verbose_name_plural": "Contact form entries",
        "ordering": ["-created_at"],
      },
    ),
    migrations.CreateModel(
      name="Education",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("institution", models.CharField(max_length=180)),
        ("degree", models.CharField(max_length=180)),
        ("field_of_study", models.CharField(blank=True, max_length=180)),
        ("location", models.CharField(blank=True, max_length=120)),
        ("start_date", models.DateField()),
        ("end_date", models.DateField(blank=True, null=True)),
        ("grade", models.CharField(blank=True, max_length=120)),
        ("description", models.TextField(blank=True)),
        ("order", models.PositiveIntegerField(default=0)),
      ],
      options={
        "ordering": ["order", "-start_date", "-id"],
      },
    ),
    migrations.CreateModel(
      name="Experience",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("title", models.CharField(max_length=140)),
        ("company", models.CharField(max_length=160)),
        ("location", models.CharField(blank=True, max_length=120)),
        ("start_date", models.DateField()),
        ("end_date", models.DateField(blank=True, null=True)),
        ("is_current", models.BooleanField(default=False)),
        ("description", models.TextField()),
        ("highlights", models.TextField(blank=True, help_text="Use one line per bullet point.")),
        ("tech_stack", models.CharField(blank=True, help_text="Comma-separated technologies.", max_length=255)),
        ("order", models.PositiveIntegerField(default=0)),
      ],
      options={
        "ordering": ["order", "-start_date", "-id"],
      },
    ),
    migrations.CreateModel(
      name="Project",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("title", models.CharField(max_length=160)),
        ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
        ("short_description", models.CharField(max_length=220)),
        ("description", models.TextField()),
        ("tech_stack", models.CharField(help_text="Comma-separated technologies.", max_length=255)),
        ("image", models.ImageField(blank=True, null=True, upload_to="projects/")),
        ("live_url", models.URLField(blank=True)),
        ("github_url", models.URLField(blank=True)),
        ("start_date", models.DateField(blank=True, null=True)),
        ("end_date", models.DateField(blank=True, null=True)),
        ("is_featured", models.BooleanField(default=True)),
        ("order", models.PositiveIntegerField(default=0)),
      ],
      options={
        "ordering": ["order", "-start_date", "-id"],
      },
    ),
    migrations.CreateModel(
      name="Skill",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("name", models.CharField(max_length=100)),
        (
          "category",
          models.CharField(
            choices=[
              ("backend", "Backend"),
              ("ai", "AI and LLM"),
              ("database", "Databases"),
              ("devops", "Cloud and DevOps"),
              ("frontend", "Frontend"),
              ("tools", "Tools"),
              ("soft", "Soft Skills"),
            ],
            default="backend",
            max_length=20,
          ),
        ),
        (
          "level",
          models.CharField(
            choices=[
              ("intermediate", "Intermediate"),
              ("advanced", "Advanced"),
              ("expert", "Expert"),
            ],
            default="advanced",
            max_length=20,
          ),
        ),
        ("order", models.PositiveIntegerField(default=0)),
      ],
      options={
        "ordering": ["order", "name"],
      },
    ),
  ]
